---
title: "ggplot Homework"
output: html_notebook
---

```{r}
library(ggplot2)
library(CodeClanData)
library(tidyverse)
```
Sources of revenue across 2018 and 2019
```{r}
ggplot(qb_revenue_breakdown) +
  aes(x = Year, y = Revenue, fill = Product) +
  geom_bar(stat = "identity") +
  labs(x = "Year",
       y = "Revenue", 
       title = "Sources of Revenue",
       subtitle = "Across 2018 and 2019",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_fill_manual(
          values = c(
              "Accessories" = "#E89FE9",
              "Smart Watches" = "#50434F",
              "Subscription Services" = "#B6A7B5",
              "Trackers" = "#F9A472")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```

Monthly sales of "flagship product" - the KwikBit Unit 1 - over the last year
```{r}
ggplot(qb_monthly_sales) +
  aes(x = Date, y = Amount, colour = Cashflow) +
  geom_line(data = subset(qb_monthly_sales, 
                          Cashflow == "Kwikbit Unit 1 Sales")) +
  labs(x = "Date",
       y = "Amount", 
       title = "Monthly Sales of flagship product\nover the last year",
       subtitle = "the KwikBit Unit 1",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_color_manual(
          values = c(
              "#E89FE9")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```
Monthly revenue and costs over the last year
```{r}
ggplot(qb_monthly_sales) +
  aes(x = Date, y = Amount, colour = Cashflow) +
  geom_line(data = subset(qb_monthly_sales, 
                          Cashflow == "Cost" | Cashflow == "Total Revenue")) +
   labs(x = "Date",
       y = "Amount", 
       title = "Monthly Revenue and Costs",
       subtitle = "Over the last year",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_color_manual(
          values = c(
              "#E89FE9", "#F9A472")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```
Annual sales of personal fitness trackers over the last 5 years by company
```{r}
ggplot(qb_competitors) +
  aes(x = Year, y = Revenue, fill = Company) +
  geom_area(position = "identity", alpha = 0.3) +
  labs(x = "Year",
       y = "Revenue", 
       title = "Annual Sales of \nPerson Fitness Trackers",
       subtitle = "Over the last 5 years \nby company",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_fill_manual(
          values = c(
              "#E89FE9",
              "#50434F",
              "#B6A7B5",
              "#F9A472")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```
Sales from 5 competitors
```{r}
ggplot(qb_competitors) +
  geom_line(aes(x = Year, 
                y = Revenue, 
                group = Company, 
                colour = Company), alpha = 0.35) +
  geom_point(aes(x = Year, 
                 y = Revenue, 
                 colour = Company), alpha = 0.5) +
  labs(x = "Date",
       y = "Amount", 
       title = "Sales",
       subtitle = "From four competitors",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_color_manual(
          values = c(
              "#E89FE9",
              "#50434F",
              "#B6A7B5",
              "#F9A472")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```


```{r}
device.labs <- c("Device: QikBit1", "Device: Comp#1", "Device: Comp#2", "Device: Comp#3")
names(device.labs) <- c("qikbit1", "competitor1", "competitor2", "competitor3")

person.labs <- c("Id.#1", "Id.#2", "Id.#3", "Id.#4", "Id.#5")
names(person.labs) <- c("person1", "person2", "person3", "person4", "person5")

qb_device_data %>%
  mutate(duration_mins = hours * 60 + mins) %>%
  ggplot(aes(x = duration_mins, y = counts, color = id)) +
  geom_line() +
  facet_grid(id ~ device, 
  labeller = labeller(id = person.labs, device = device.labs)) +
  labs(x = "Duration in minutes",
       y = "Step counts", 
       title = "Comparison",
       subtitle = "Between individuals and QikBit1 and competitors",
       caption = "Source: CodeClan | www.codeclan.com") +
  scale_color_manual(
          values = c(
              "#E89FE9",
              "#50434F",
              "#B6A7B5",
              "#F9A472",
              "#BD7040")) +
  theme_minimal() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.caption = element_text(size = 7)
        )
```

