---
title: "Week 2 homework"
output: html_notebook
---

#### Create a connection from R to your local acme_employees database.
```{r}
library(keyring)
library(RPostgreSQL) 
source("./scripts/api_fetcher.R")
source("./scripts/response_unpacker.R")

# connect to the postgress database
keyring_unlock(keyring = "local1")
username <- key_get("postgresql_username", keyring = "local1")
password <- key_get("postgresql_password", keyring = "local1")
acme_db_connection <- dbConnect(drv = PostgreSQL(max.con = 2), user = username, password = password, dbname = "acme_employees", host = "localhost")
keyring_lock(keyring = "local1")
rm(list = c("username", "password"))
```
  
#### Explore sql data

#### Assign the sql query data to "employees_with_feedbacks"
```{r echo=TRUE}
employees_with_teams_feedbacks <- dbGetQuery(acme_db_connection,"
            SELECT f.*, e.*, t.* 
            FROM (feedbacks AS f INNER JOIN employees AS e
            ON f.employee_id = e.id)
            INNER JOIN teams AS t 
            ON e.team_id = t.id;
           ")
```
  
#### Disconnect from acme_employees database
```{r}
# run this to disconnect from the acme_employees sql database when 
# finished with the query
dbDisconnect(conn = acme_db_connection)
```
  
#### Get credentials for the API
```{r}
keyring_unlock("api")
indico_api_key <- key_get("indico_api", keyring = "api")
keyring_lock(keyring = "api")
```
  
#### set the url for the API service
```{r}
url <- "https://apiv2.indico.io/emotion"
```
  
#### Set-up empty dataframe to hold emotions
```{r}
empty <- rep(NA, nrow(employees_with_teams_feedbacks))
api_results <- data.frame(anger = empty, fear = empty, joy = empty,
                          sadness = empty, surprise = empty)
```
  
#### Fetch a vector of emotions values from Indico API for each feedback message
```{r}

for (row in 1:nrow(employees_with_teams_feedbacks)){
  # get message for this employee
  message <- employees_with_teams_feedbacks[row, "message"]
}

response_list <- api_fetcher(url, indico_api_key, message)

emotion_vec <- response_unpacker(response_list)

# insert the emotion vector for the current employee into the data frame
api_results[row, ] <- emotion_vec

# join API results to original data frame
employees_with_teams_feedbacks_api <- cbind(employees_with_teams_feedbacks, api_results)

```

```{r}
# write to csv file in data/processed
write_csv(employees_with_teams_feedbacks_api, "./data/processed/employees_with_teams_feedbacks.csv")
write_json(employees_with_teams_feedbacks_api, "./data/processed/employees_with_teams_feedbacks.json")
```
